"""Chore: Delete Age, Update Child field in User

Revision ID: 016c57464b76
Revises: 7321992fae47
Create Date: 2025-03-16 21:55:46.427178

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "016c57464b76"
down_revision = "7321992fae47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("age")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "age",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("year", sa.SMALLINT(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_age"),
    )
    # ### end Alembic commands ###
