"""feat: add ChildSavingPlan, ChildSavingAmountEntry, and Revised Child

Revision ID: 0819365613e1
Revises: 3ab0fb8bd1f6
Create Date: 2025-04-12 21:04:36.005758

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0819365613e1"
down_revision = "3ab0fb8bd1f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "child_saving_plan",
        sa.Column("id", sa.String(length=13), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_child_saving_plan")),
    )
    with op.batch_alter_table("child_saving_plan", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_child_saving_plan_name"), ["name"], unique=False
        )

    op.create_table(
        "child_saving_amount_entry",
        sa.Column("age", sa.SmallInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("child_saving_plan_id", sa.String(length=13), nullable=False),
        sa.Column("id", sa.String(length=13), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_saving_plan_id"],
            ["child_saving_plan.id"],
            name=op.f(
                "fk_child_saving_amount_entry_child_saving_plan_id_child_saving_plan"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_child_saving_amount_entry")),
    )
    with op.batch_alter_table("child_saving_amount_entry", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_child_saving_amount_entry_amount"), ["amount"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_child_saving_amount_entry_child_saving_plan_id"),
            ["child_saving_plan_id"],
            unique=False,
        )

    with op.batch_alter_table("child", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("child_saving_plan_id", sa.String(length=13), nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_child_child_saving_plan_id"),
            ["child_saving_plan_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_child_child_saving_plan_id_child_saving_plan"),
            "child_saving_plan",
            ["child_saving_plan_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("child", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_child_child_saving_plan_id_child_saving_plan"),
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_child_child_saving_plan_id"))
        batch_op.drop_column("child_saving_plan_id")

    with op.batch_alter_table("child_saving_amount_entry", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_child_saving_amount_entry_child_saving_plan_id")
        )
        batch_op.drop_index(batch_op.f("ix_child_saving_amount_entry_amount"))

    op.drop_table("child_saving_amount_entry")
    with op.batch_alter_table("child_saving_plan", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_child_saving_plan_name"))

    op.drop_table("child_saving_plan")
    # ### end Alembic commands ###
