"""chore: add owner_id filed for ChildSavingPlan

Revision ID: 3488c09c67e9
Revises: 0819365613e1
Create Date: 2025-04-13 14:39:07.020523

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3488c09c67e9"
down_revision = "0819365613e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("child_saving_plan", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_id", sa.String(length=13), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_child_saving_plan_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_child_saving_plan_owner_id_account"),
            "account",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("child_saving_plan", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_child_saving_plan_owner_id_account"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_child_saving_plan_owner_id"))
        batch_op.drop_column("owner_id")

    # ### end Alembic commands ###
