"""revised: Drop max, min loss from Risk, and add amount and probability

Revision ID: 3ab0fb8bd1f6
Revises: 96d38ee967b6
Create Date: 2025-04-11 20:58:12.947915

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ab0fb8bd1f6"
down_revision = "96d38ee967b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk", schema=None) as batch_op:
        batch_op.add_column(sa.Column("amount", sa.BigInteger(), nullable=False))
        batch_op.add_column(
            sa.Column("probability", sa.DECIMAL(precision=5, scale=2), nullable=False)
        )
        batch_op.drop_column("max_loss")
        batch_op.drop_column("min_loss")

    with op.batch_alter_table("scenario_risk", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("probability", sa.DECIMAL(precision=5, scale=2), nullable=True)
        )
        batch_op.drop_column("max_loss")
        batch_op.drop_column("min_loss")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario_risk", schema=None) as batch_op:
        batch_op.add_column(sa.Column("min_loss", sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column("max_loss", sa.BIGINT(), nullable=True))
        batch_op.drop_column("probability")

    with op.batch_alter_table("risk", schema=None) as batch_op:
        batch_op.add_column(sa.Column("min_loss", sa.BIGINT(), nullable=False))
        batch_op.add_column(sa.Column("max_loss", sa.BIGINT(), nullable=False))
        batch_op.drop_column("probability")
        batch_op.drop_column("amount")

    # ### end Alembic commands ###
