"""change username to name, and make it non-unique and non-indexed. Name is display-only purpose, not for lookup or identification

Revision ID: 40cc7fe31d04
Revises: 6a32492c6ceb
Create Date: 2025-03-31 17:33:51.201091

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "40cc7fe31d04"
down_revision = "6a32492c6ceb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=64), nullable=False))
        batch_op.drop_index("ix_account_username")
        batch_op.drop_column("username")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("username", sa.VARCHAR(length=64), nullable=False)
        )
        batch_op.create_index("ix_account_username", ["username"], unique=1)
        batch_op.drop_column("name")

    # ### end Alembic commands ###
