"""revised left id to scenario_id in ScenarioExpense

Revision ID: 6a32492c6ceb
Revises: c7376fb6bff6
Create Date: 2025-03-28 09:39:50.617075

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a32492c6ceb"
down_revision = "c7376fb6bff6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario_expense", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("scenario_id", sa.String(length=13), nullable=False)
        )
        batch_op.drop_constraint(
            "fk_scenario_expense_left_id_scenario", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_expense_scenario_id_scenario"),
            "scenario",
            ["scenario_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("left_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario_expense", schema=None) as batch_op:
        batch_op.add_column(sa.Column("left_id", sa.VARCHAR(length=13), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_expense_scenario_id_scenario"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_expense_left_id_scenario",
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("scenario_id")

    # ### end Alembic commands ###
