"""Update: Schema v0.2

Revision ID: 7321992fae47
Revises: 7319e6001c3b
Create Date: 2025-03-16 00:12:33.553354

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7321992fae47"
down_revision = "7319e6001c3b"
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=13), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account")),
    )
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_account_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_account_username"), ["username"], unique=True
        )

    op.create_table(
        "asset",
        sa.Column(
            "max_yearly_return_rate", sa.DECIMAL(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "min_yearly_return_rate", sa.DECIMAL(precision=5, scale=2), nullable=False
        ),
        sa.Column("owner_id", sa.String(length=13), nullable=False),
        sa.Column("id", sa.String(length=13), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("start_age", sa.SmallInteger(), nullable=False),
        sa.Column("end_age", sa.SmallInteger(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["account.id"], name=op.f("fk_asset_owner_id_account")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset")),
    )
    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_asset_amount"), ["amount"], unique=False)
        batch_op.create_index(batch_op.f("ix_asset_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_asset_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "income",
        sa.Column("owner_id", sa.String(length=13), nullable=False),
        sa.Column("id", sa.String(length=13), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("start_age", sa.SmallInteger(), nullable=False),
        sa.Column("end_age", sa.SmallInteger(), nullable=True),
        sa.Column(
            "max_yearly_growth_rate", sa.DECIMAL(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "min_yearly_growth_rate", sa.DECIMAL(precision=5, scale=2), nullable=False
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["account.id"], name=op.f("fk_income_owner_id_account")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_income")),
    )
    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_income_amount"), ["amount"], unique=False)
        batch_op.create_index(batch_op.f("ix_income_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_income_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "liability",
        sa.Column("principal_amount", sa.BigInteger(), nullable=False),
        sa.Column("interest_rate", sa.DECIMAL(precision=5, scale=2), nullable=False),
        sa.Column("start_age", sa.SmallInteger(), nullable=False),
        sa.Column("end_age", sa.SmallInteger(), nullable=False),
        sa.Column("owner_id", sa.String(length=13), nullable=False),
        sa.Column("id", sa.String(length=13), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["account.id"], name=op.f("fk_liability_owner_id_account")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_liability")),
    )
    with op.batch_alter_table("liability", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_liability_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_liability_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "risk",
        sa.Column("max_loss", sa.BigInteger(), nullable=False),
        sa.Column("min_loss", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.String(length=13), nullable=False),
        sa.Column("id", sa.String(length=13), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_age", sa.SmallInteger(), nullable=False),
        sa.Column("end_age", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["account.id"], name=op.f("fk_risk_owner_id_account")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk")),
    )
    with op.batch_alter_table("risk", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_risk_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_risk_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "scenario_asset",
        sa.Column(
            "max_yearly_return_rate", sa.DECIMAL(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "min_yearly_return_rate", sa.DECIMAL(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "allocation_percentage", sa.DECIMAL(precision=3, scale=2), nullable=False
        ),
        sa.Column("left_id", sa.String(length=13), nullable=False),
        sa.Column("right_id", sa.String(length=13), nullable=False),
        sa.Column("start_age", sa.SmallInteger(), nullable=True),
        sa.Column("end_age", sa.SmallInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["left_id"],
            ["scenario.id"],
            name=op.f("fk_scenario_asset_left_id_scenario"),
        ),
        sa.ForeignKeyConstraint(
            ["right_id"], ["asset.id"], name=op.f("fk_scenario_asset_right_id_asset")
        ),
        sa.PrimaryKeyConstraint("left_id", "right_id", name=op.f("pk_scenario_asset")),
    )
    op.create_table(
        "scenario_income",
        sa.Column("left_id", sa.String(length=13), nullable=False),
        sa.Column("right_id", sa.String(length=13), nullable=False),
        sa.Column("start_age", sa.SmallInteger(), nullable=True),
        sa.Column("end_age", sa.SmallInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "max_yearly_growth_rate", sa.DECIMAL(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "min_yearly_growth_rate", sa.DECIMAL(precision=5, scale=2), nullable=False
        ),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["left_id"],
            ["scenario.id"],
            name=op.f("fk_scenario_income_left_id_scenario"),
        ),
        sa.ForeignKeyConstraint(
            ["right_id"], ["income.id"], name=op.f("fk_scenario_income_right_id_income")
        ),
        sa.PrimaryKeyConstraint("left_id", "right_id", name=op.f("pk_scenario_income")),
    )
    op.create_table(
        "scenario_liability",
        sa.Column("interest_rate", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column(
            "allocation_percentage", sa.DECIMAL(precision=3, scale=2), nullable=False
        ),
        sa.Column("left_id", sa.String(length=13), nullable=False),
        sa.Column("right_id", sa.String(length=13), nullable=False),
        sa.Column("start_age", sa.SmallInteger(), nullable=True),
        sa.Column("end_age", sa.SmallInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["left_id"],
            ["scenario.id"],
            name=op.f("fk_scenario_liability_left_id_scenario"),
        ),
        sa.ForeignKeyConstraint(
            ["right_id"],
            ["liability.id"],
            name=op.f("fk_scenario_liability_right_id_liability"),
        ),
        sa.PrimaryKeyConstraint(
            "left_id", "right_id", name=op.f("pk_scenario_liability")
        ),
    )
    op.create_table(
        "scenario_risk",
        sa.Column("max_loss", sa.BigInteger(), nullable=True),
        sa.Column("min_loss", sa.BigInteger(), nullable=True),
        sa.Column("left_id", sa.String(length=13), nullable=False),
        sa.Column("right_id", sa.String(length=13), nullable=False),
        sa.Column("start_age", sa.SmallInteger(), nullable=True),
        sa.Column("end_age", sa.SmallInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["left_id"], ["scenario.id"], name=op.f("fk_scenario_risk_left_id_scenario")
        ),
        sa.ForeignKeyConstraint(
            ["right_id"], ["risk.id"], name=op.f("fk_scenario_risk_right_id_risk")
        ),
        sa.PrimaryKeyConstraint("left_id", "right_id", name=op.f("pk_scenario_risk")),
    )
    with op.batch_alter_table("salary", schema=None) as batch_op:
        batch_op.drop_index("ix_salary_owner_id")

    # Alter table first
    with op.batch_alter_table("child", schema=None) as batch_op:
        batch_op.add_column(sa.Column("birth_age", sa.SmallInteger(), nullable=False))
        batch_op.add_column(
            sa.Column("independent_age", sa.SmallInteger(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("parent_id", sa.String(length=13), nullable=False)
        )
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=128),
            existing_nullable=False,
        )
        batch_op.drop_index("ix_child_owner_id")
        batch_op.create_index(batch_op.f("ix_child_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_child_parent_id"), ["parent_id"], unique=False
        )
        batch_op.drop_constraint("fk_child_independent_year_age", type_="foreignkey")
        batch_op.drop_constraint("fk_child_owner_id_user", type_="foreignkey")
        batch_op.drop_constraint("fk_child_born_at_age_age", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_child_parent_id_account"), "account", ["parent_id"], ["id"]
        )
        batch_op.drop_column("updated")
        batch_op.drop_column("born_at_age")
        batch_op.drop_column("created")
        batch_op.drop_column("owner_id")
        batch_op.drop_column("independent_year")

    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("start_age", sa.SmallInteger(), nullable=False))
        batch_op.add_column(sa.Column("end_age", sa.SmallInteger(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "max_yearly_growth_rate",
                sa.DECIMAL(precision=5, scale=2),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "min_yearly_growth_rate",
                sa.DECIMAL(precision=5, scale=2),
                nullable=False,
            )
        )
        batch_op.alter_column(
            "owner_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=128),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "amount",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )
        batch_op.create_index(batch_op.f("ix_expense_amount"), ["amount"], unique=False)
        batch_op.create_index(batch_op.f("ix_expense_name"), ["name"], unique=False)
        batch_op.drop_constraint("fk_expense_owner_id_user", type_="foreignkey")
        batch_op.drop_constraint("fk_expense_end_year_age", type_="foreignkey")
        batch_op.drop_constraint("fk_expense_start_year_age", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_expense_owner_id_account"), "account", ["owner_id"], ["id"]
        )
        batch_op.drop_column("created")
        batch_op.drop_column("start_year")
        batch_op.drop_column("updated")
        batch_op.drop_column("end_year")

    with op.batch_alter_table("house", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("interest_rate", sa.DECIMAL(precision=5, scale=2), nullable=False)
        )
        batch_op.add_column(
            sa.Column("purchase_age", sa.SmallInteger(), nullable=False)
        )
        batch_op.add_column(sa.Column("sale_age", sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.alter_column(
            "down_payment",
            existing_type=sa.NUMERIC(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "loan_term",
            existing_type=sa.INTEGER(),
            type_=sa.SmallInteger(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "owner_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=128),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "amount",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )
        batch_op.create_index(batch_op.f("ix_house_amount"), ["amount"], unique=False)
        batch_op.create_index(batch_op.f("ix_house_name"), ["name"], unique=False)
        batch_op.drop_constraint("fk_house_buy_at_age_age", type_="foreignkey")
        batch_op.drop_constraint("fk_house_owner_id_user", type_="foreignkey")
        batch_op.drop_constraint("fk_house_sell_at_age_age", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_house_owner_id_account"), "account", ["owner_id"], ["id"]
        )
        batch_op.drop_column("buy_at_age")
        batch_op.drop_column("sell_at_age")
        batch_op.drop_column("updated")
        batch_op.drop_column("created")
        batch_op.drop_column("interest")

    with op.batch_alter_table("scenario", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "asset_allocation_percentage",
                sa.DECIMAL(precision=3, scale=2),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.alter_column(
            "retire_age",
            existing_type=sa.INTEGER(),
            type_=sa.SmallInteger(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "owner_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=128),
            existing_nullable=False,
        )
        batch_op.drop_index("ix_scenario_accident_id")
        batch_op.drop_index("ix_scenario_retire_age")
        batch_op.create_index(batch_op.f("ix_scenario_name"), ["name"], unique=False)
        batch_op.drop_constraint("fk_scenario_retire_age_age", type_="foreignkey")
        batch_op.drop_constraint("fk_scenario_owner_id_user", type_="foreignkey")
        batch_op.drop_constraint("fk_scenario_accident_id_accident", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_owner_id_account"), "account", ["owner_id"], ["id"]
        )
        batch_op.drop_column("created")
        batch_op.drop_column("updated")
        batch_op.drop_column("investment_ratio")
        batch_op.drop_column("accident_id")

    with op.batch_alter_table("scenario_child", schema=None) as batch_op:
        batch_op.add_column(sa.Column("birth_age", sa.SmallInteger(), nullable=True))
        batch_op.add_column(
            sa.Column("independent_age", sa.SmallInteger(), nullable=True)
        )
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("memo", sa.Text(), nullable=True))
        batch_op.alter_column(
            "left_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "right_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.drop_constraint(
            "fk_scenario_child_independent_year_age", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_scenario_child_born_at_age_age", type_="foreignkey"
        )
        batch_op.drop_column("independent_year")
        batch_op.drop_column("born_at_age")

    with op.batch_alter_table("scenario_expense", schema=None) as batch_op:
        batch_op.add_column(sa.Column("start_age", sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column("end_age", sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "max_yearly_growth_rate",
                sa.DECIMAL(precision=5, scale=2),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "min_yearly_growth_rate",
                sa.DECIMAL(precision=5, scale=2),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("memo", sa.Text(), nullable=True))
        batch_op.alter_column(
            "left_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "right_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.drop_constraint("fk_scenario_expense_end_year_age", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_scenario_expense_start_year_age", type_="foreignkey"
        )
        batch_op.drop_column("upper_raise_rate")
        batch_op.drop_column("lower_raise_rate")
        batch_op.drop_column("start_year")
        batch_op.drop_column("end_year")

    with op.batch_alter_table("scenario_house", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("interest_rate", sa.DECIMAL(precision=5, scale=2), nullable=True)
        )
        batch_op.add_column(sa.Column("purchase_age", sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column("sale_age", sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("memo", sa.Text(), nullable=True))
        batch_op.alter_column(
            "left_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "right_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "down_payment",
            existing_type=sa.NUMERIC(),
            type_=sa.BigInteger(),
            nullable=True,
        )
        batch_op.alter_column(
            "loan_term",
            existing_type=sa.INTEGER(),
            type_=sa.SmallInteger(),
            nullable=True,
        )
        batch_op.drop_constraint("fk_scenario_house_buy_at_age_age", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_scenario_house_sell_at_age_age", type_="foreignkey"
        )
        batch_op.drop_column("buy_at_age")
        batch_op.drop_column("interest")
        batch_op.drop_column("sell_at_age")

    # Drop table last to prevent table not existed issue
    op.drop_table("salary")
    op.drop_table("scenario_salary")
    with op.batch_alter_table("investment", schema=None) as batch_op:
        batch_op.drop_index("ix_investment_owner_id")

    op.drop_table("investment")
    op.drop_table("scenario_investment")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index("ix_user_email")
        batch_op.drop_index("ix_user_username")

    op.drop_table("user")
    with op.batch_alter_table("accident", schema=None) as batch_op:
        batch_op.drop_index("ix_accident_owner_id")

    op.drop_table("accident")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Tables first
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(length=64), nullable=False),
        sa.Column("email", sa.VARCHAR(length=120), nullable=False),
        sa.Column("password_hash", sa.VARCHAR(length=256), nullable=True),
        sa.Column("about_me", sa.VARCHAR(length=140), nullable=True),
        sa.Column("last_seen", sa.DATETIME(), nullable=True),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_user"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index("ix_user_username", ["username"], unique=1)
        batch_op.create_index("ix_user_email", ["email"], unique=1)

    op.create_table(
        "accident",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("upper_from_salary_ratio", sa.NUMERIC(), nullable=False),
        sa.Column("lower_from_salary_ratio", sa.NUMERIC(), nullable=False),
        sa.Column("owner_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="fk_accident_owner_id_user"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_accident"),
    )

    op.create_table(
        "investment",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("amount", sa.INTEGER(), nullable=False),
        sa.Column("owner_id", sa.INTEGER(), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.Column("start_year", sa.INTEGER(), nullable=False),
        sa.Column("end_year", sa.INTEGER(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=64), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["end_year"], ["age.id"], name="fk_investment_end_year_age"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="fk_investment_owner_id_user"
        ),
        sa.ForeignKeyConstraint(
            ["start_year"], ["age.id"], name="fk_investment_start_year_age"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_investment"),
    )
    with op.batch_alter_table("investment", schema=None) as batch_op:
        batch_op.create_index("ix_investment_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "scenario_investment",
        sa.Column("left_id", sa.INTEGER(), nullable=False),
        sa.Column("right_id", sa.INTEGER(), nullable=False),
        sa.Column("upper_return_rate", sa.NUMERIC(), nullable=False),
        sa.Column("lower_return_rate", sa.NUMERIC(), nullable=False),
        sa.Column("percentage_from_saving", sa.NUMERIC(), nullable=False),
        sa.Column("start_year", sa.INTEGER(), nullable=False),
        sa.Column("end_year", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["end_year"], ["age.id"], name="fk_scenario_investment_end_year_age"
        ),
        sa.ForeignKeyConstraint(
            ["left_id"], ["scenario.id"], name="fk_scenario_investment_left_id_scenario"
        ),
        sa.ForeignKeyConstraint(
            ["right_id"],
            ["investment.id"],
            name="fk_scenario_investment_right_id_investment",
        ),
        sa.ForeignKeyConstraint(
            ["start_year"], ["age.id"], name="fk_scenario_investment_start_year_age"
        ),
        sa.PrimaryKeyConstraint("left_id", "right_id", name="pk_scenario_investment"),
    )

    op.create_table(
        "salary",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("amount", sa.INTEGER(), nullable=False),
        sa.Column("owner_id", sa.INTEGER(), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.Column("start_year", sa.INTEGER(), nullable=False),
        sa.Column("end_year", sa.INTEGER(), nullable=True),
        sa.Column("name", sa.VARCHAR(length=64), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["end_year"], ["age.id"], name="fk_salary_end_year_age"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="fk_salary_owner_id_user"
        ),
        sa.ForeignKeyConstraint(
            ["start_year"], ["age.id"], name="fk_salary_start_year_age"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_salary"),
    )
    with op.batch_alter_table("salary", schema=None) as batch_op:
        batch_op.create_index("ix_salary_owner_id", ["owner_id"], unique=False)

    op.create_table(
        "scenario_salary",
        sa.Column("left_id", sa.INTEGER(), nullable=False),
        sa.Column("right_id", sa.INTEGER(), nullable=False),
        sa.Column("upper_raise_rate", sa.NUMERIC(), nullable=False),
        sa.Column("lower_raise_rate", sa.NUMERIC(), nullable=False),
        sa.Column("start_year", sa.INTEGER(), nullable=False),
        sa.Column("end_year", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["end_year"], ["age.id"], name="fk_scenario_salary_end_year_age"
        ),
        sa.ForeignKeyConstraint(
            ["left_id"], ["scenario.id"], name="fk_scenario_salary_left_id_scenario"
        ),
        sa.ForeignKeyConstraint(
            ["right_id"], ["salary.id"], name="fk_scenario_salary_right_id_salary"
        ),
        sa.ForeignKeyConstraint(
            ["start_year"], ["age.id"], name="fk_scenario_salary_start_year_age"
        ),
        sa.PrimaryKeyConstraint("left_id", "right_id", name="pk_scenario_salary"),
    )

    # Alter Table Second
    with op.batch_alter_table("accident", schema=None) as batch_op:
        batch_op.create_index("ix_accident_owner_id", ["owner_id"], unique=False)

    with op.batch_alter_table("scenario_house", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sell_at_age", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("interest", sa.NUMERIC(), nullable=False))
        batch_op.add_column(sa.Column("buy_at_age", sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(
            "fk_scenario_house_sell_at_age_age", "age", ["sell_at_age"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_house_buy_at_age_age", "age", ["buy_at_age"], ["id"]
        )
        batch_op.alter_column(
            "loan_term",
            existing_type=sa.SmallInteger(),
            type_=sa.INTEGER(),
            nullable=False,
        )
        batch_op.alter_column(
            "down_payment",
            existing_type=sa.BigInteger(),
            type_=sa.NUMERIC(),
            nullable=False,
        )
        batch_op.alter_column(
            "right_id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "left_id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.drop_column("memo")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("sale_age")
        batch_op.drop_column("purchase_age")
        batch_op.drop_column("interest_rate")

    with op.batch_alter_table("scenario_expense", schema=None) as batch_op:
        batch_op.add_column(sa.Column("end_year", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("start_year", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("lower_raise_rate", sa.NUMERIC(), nullable=False))
        batch_op.add_column(sa.Column("upper_raise_rate", sa.NUMERIC(), nullable=False))
        batch_op.create_foreign_key(
            "fk_scenario_expense_start_year_age", "age", ["start_year"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_expense_end_year_age", "age", ["end_year"], ["id"]
        )
        batch_op.alter_column(
            "right_id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "left_id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.drop_column("memo")
        batch_op.drop_column("min_yearly_growth_rate")
        batch_op.drop_column("max_yearly_growth_rate")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("end_age")
        batch_op.drop_column("start_age")

    with op.batch_alter_table("scenario_child", schema=None) as batch_op:
        batch_op.add_column(sa.Column("born_at_age", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("independent_year", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            "fk_scenario_child_born_at_age_age", "age", ["born_at_age"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_child_independent_year_age",
            "age",
            ["independent_year"],
            ["id"],
        )
        batch_op.alter_column(
            "right_id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "left_id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.drop_column("memo")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("independent_age")
        batch_op.drop_column("birth_age")

    with op.batch_alter_table("scenario", schema=None) as batch_op:
        batch_op.add_column(sa.Column("accident_id", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("investment_ratio", sa.NUMERIC(), nullable=False))
        batch_op.add_column(sa.Column("updated", sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column("created", sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_owner_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_accident_id_accident", "accident", ["accident_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_owner_id_user", "user", ["owner_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_retire_age_age", "age", ["retire_age"], ["id"]
        )
        batch_op.drop_index(batch_op.f("ix_scenario_name"))
        batch_op.create_index("ix_scenario_retire_age", ["retire_age"], unique=False)
        batch_op.create_index("ix_scenario_accident_id", ["accident_id"], unique=False)
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "owner_id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "retire_age",
            existing_type=sa.SmallInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("asset_allocation_percentage")

    with op.batch_alter_table("house", schema=None) as batch_op:
        batch_op.add_column(sa.Column("interest", sa.NUMERIC(), nullable=False))
        batch_op.add_column(sa.Column("created", sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column("updated", sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column("sell_at_age", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("buy_at_age", sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_house_owner_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_house_sell_at_age_age", "age", ["sell_at_age"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_house_owner_id_user", "user", ["owner_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_house_buy_at_age_age", "age", ["buy_at_age"], ["id"]
        )
        batch_op.drop_index(batch_op.f("ix_house_name"))
        batch_op.drop_index(batch_op.f("ix_house_amount"))
        batch_op.alter_column(
            "amount",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "owner_id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "loan_term",
            existing_type=sa.SmallInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "down_payment",
            existing_type=sa.BigInteger(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("sale_age")
        batch_op.drop_column("purchase_age")
        batch_op.drop_column("interest_rate")

    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.add_column(sa.Column("end_year", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("updated", sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column("start_year", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("created", sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_expense_owner_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_expense_start_year_age", "age", ["start_year"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_expense_end_year_age", "age", ["end_year"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_expense_owner_id_user", "user", ["owner_id"], ["id"]
        )
        batch_op.drop_index(batch_op.f("ix_expense_name"))
        batch_op.drop_index(batch_op.f("ix_expense_amount"))
        batch_op.alter_column(
            "amount",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "owner_id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.drop_column("min_yearly_growth_rate")
        batch_op.drop_column("max_yearly_growth_rate")
        batch_op.drop_column("end_age")
        batch_op.drop_column("start_age")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("child", schema=None) as batch_op:
        batch_op.add_column(sa.Column("independent_year", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("owner_id", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("created", sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column("born_at_age", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("updated", sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_child_parent_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_child_born_at_age_age", "age", ["born_at_age"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_child_owner_id_user", "user", ["owner_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_child_independent_year_age", "age", ["independent_year"], ["id"]
        )
        batch_op.drop_index(batch_op.f("ix_child_parent_id"))
        batch_op.drop_index(batch_op.f("ix_child_name"))
        batch_op.create_index("ix_child_owner_id", ["owner_id"], unique=False)
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("parent_id")
        batch_op.drop_column("independent_age")
        batch_op.drop_column("birth_age")

    # Drop Table Last
    op.drop_table("scenario_risk")
    op.drop_table("scenario_liability")
    op.drop_table("scenario_income")
    op.drop_table("scenario_asset")
    with op.batch_alter_table("risk", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_owner_id"))
        batch_op.drop_index(batch_op.f("ix_risk_name"))

    op.drop_table("risk")
    with op.batch_alter_table("liability", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_liability_owner_id"))
        batch_op.drop_index(batch_op.f("ix_liability_name"))

    op.drop_table("liability")
    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_income_owner_id"))
        batch_op.drop_index(batch_op.f("ix_income_name"))
        batch_op.drop_index(batch_op.f("ix_income_amount"))

    op.drop_table("income")
    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_owner_id"))
        batch_op.drop_index(batch_op.f("ix_asset_name"))
        batch_op.drop_index(batch_op.f("ix_asset_amount"))

    op.drop_table("asset")
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_username"))
        batch_op.drop_index(batch_op.f("ix_account_email"))

    op.drop_table("account")
    ### end Alembic commands ###
