"""chore: change independent_age from child to saving plan

Revision ID: 8ca1f6345a5c
Revises: 3488c09c67e9
Create Date: 2025-04-13 16:03:25.229873

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ca1f6345a5c"
down_revision = "3488c09c67e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("child", schema=None) as batch_op:
        batch_op.drop_column("independent_age")

    with op.batch_alter_table("child_saving_amount_entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("start_age", sa.SmallInteger(), nullable=False))
        batch_op.add_column(sa.Column("end_age", sa.SmallInteger(), nullable=False))
        batch_op.add_column(sa.Column("name", sa.String(length=128), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_child_saving_amount_entry_name"), ["name"], unique=False
        )
        batch_op.drop_column("age")

    with op.batch_alter_table("child_saving_plan", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("independent_age", sa.SmallInteger(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("child_saving_plan", schema=None) as batch_op:
        batch_op.drop_column("independent_age")

    with op.batch_alter_table("child_saving_amount_entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("age", sa.SMALLINT(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_child_saving_amount_entry_name"))
        batch_op.drop_column("name")
        batch_op.drop_column("end_age")
        batch_op.drop_column("start_age")

    with op.batch_alter_table("child", schema=None) as batch_op:
        batch_op.add_column(sa.Column("independent_age", sa.SMALLINT(), nullable=False))

    # ### end Alembic commands ###
