"""feat: change end_age, sale_age, independent_age to required

Revision ID: 96d38ee967b6
Revises: 40cc7fe31d04
Create Date: 2025-04-04 21:29:19.774862

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96d38ee967b6"
down_revision = "40cc7fe31d04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.alter_column("end_age", existing_type=sa.SMALLINT(), nullable=False)

    with op.batch_alter_table("child", schema=None) as batch_op:
        batch_op.alter_column(
            "independent_age", existing_type=sa.SMALLINT(), nullable=False
        )

    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.alter_column("end_age", existing_type=sa.SMALLINT(), nullable=False)

    with op.batch_alter_table("house", schema=None) as batch_op:
        batch_op.alter_column("sale_age", existing_type=sa.SMALLINT(), nullable=False)

    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.alter_column("end_age", existing_type=sa.SMALLINT(), nullable=False)

    with op.batch_alter_table("risk", schema=None) as batch_op:
        batch_op.alter_column("end_age", existing_type=sa.SMALLINT(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("risk", schema=None) as batch_op:
        batch_op.alter_column("end_age", existing_type=sa.SMALLINT(), nullable=True)

    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.alter_column("end_age", existing_type=sa.SMALLINT(), nullable=True)

    with op.batch_alter_table("house", schema=None) as batch_op:
        batch_op.alter_column("sale_age", existing_type=sa.SMALLINT(), nullable=True)

    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.alter_column("end_age", existing_type=sa.SMALLINT(), nullable=True)

    with op.batch_alter_table("child", schema=None) as batch_op:
        batch_op.alter_column(
            "independent_age", existing_type=sa.SMALLINT(), nullable=True
        )

    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.alter_column("end_age", existing_type=sa.SMALLINT(), nullable=True)

    # ### end Alembic commands ###
