"""Revised One-to-Many Relationship (Account) and Many-to-Many Relationship (Scenario) for cascade deletion

Revision ID: b94ab48ea8cc
Revises: edb02e791617
Create Date: 2025-03-25 11:51:32.777520

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "b94ab48ea8cc"
down_revision = "edb02e791617"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.drop_constraint("fk_asset_owner_id_account", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_asset_owner_id_account"),
            "account",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("child", schema=None) as batch_op:
        batch_op.drop_constraint("fk_child_parent_id_account", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_child_parent_id_account"),
            "account",
            ["parent_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.drop_constraint("fk_expense_owner_id_account", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_expense_owner_id_account"),
            "account",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("house", schema=None) as batch_op:
        batch_op.drop_constraint("fk_house_owner_id_account", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_house_owner_id_account"),
            "account",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.drop_constraint("fk_income_owner_id_account", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_income_owner_id_account"),
            "account",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("liability", schema=None) as batch_op:
        batch_op.drop_constraint("fk_liability_owner_id_account", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_liability_owner_id_account"),
            "account",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("risk", schema=None) as batch_op:
        batch_op.drop_constraint("fk_risk_owner_id_account", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_risk_owner_id_account"),
            "account",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scenario", schema=None) as batch_op:
        batch_op.drop_constraint("fk_scenario_owner_id_account", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_owner_id_account"),
            "account",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scenario_asset", schema=None) as batch_op:
        batch_op.drop_constraint("fk_scenario_asset_right_id_asset", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_scenario_asset_left_id_scenario", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_asset_left_id_scenario"),
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_asset_right_id_asset"),
            "asset",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scenario_child", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_scenario_child_left_id_scenario", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_scenario_child_right_id_child", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_child_right_id_child"),
            "child",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_child_left_id_scenario"),
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scenario_expense", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_scenario_expense_right_id_expense", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_scenario_expense_left_id_scenario", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_expense_left_id_scenario"),
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_expense_right_id_expense"),
            "expense",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scenario_house", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_scenario_house_left_id_scenario", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_scenario_house_right_id_house", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_house_right_id_house"),
            "house",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_house_left_id_scenario"),
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scenario_income", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_scenario_income_left_id_scenario", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_scenario_income_right_id_income", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_income_right_id_income"),
            "income",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_income_left_id_scenario"),
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scenario_liability", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_scenario_liability_right_id_liability", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_scenario_liability_left_id_scenario", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_liability_left_id_scenario"),
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_liability_right_id_liability"),
            "liability",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scenario_risk", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_scenario_risk_left_id_scenario", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_scenario_risk_right_id_risk", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_risk_right_id_risk"),
            "risk",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_risk_left_id_scenario"),
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario_risk", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_risk_left_id_scenario"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_risk_right_id_risk"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_risk_right_id_risk", "risk", ["right_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_risk_left_id_scenario", "scenario", ["left_id"], ["id"]
        )

    with op.batch_alter_table("scenario_liability", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_liability_right_id_liability"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_liability_left_id_scenario"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_liability_left_id_scenario", "scenario", ["left_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_liability_right_id_liability",
            "liability",
            ["right_id"],
            ["id"],
        )

    with op.batch_alter_table("scenario_income", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_income_left_id_scenario"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_income_right_id_income"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_income_right_id_income", "income", ["right_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_income_left_id_scenario", "scenario", ["left_id"], ["id"]
        )

    with op.batch_alter_table("scenario_house", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_house_left_id_scenario"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_house_right_id_house"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_house_right_id_house", "house", ["right_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_house_left_id_scenario", "scenario", ["left_id"], ["id"]
        )

    with op.batch_alter_table("scenario_expense", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_expense_right_id_expense"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_expense_left_id_scenario"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_expense_left_id_scenario", "scenario", ["left_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_expense_right_id_expense", "expense", ["right_id"], ["id"]
        )

    with op.batch_alter_table("scenario_child", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_child_left_id_scenario"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_child_right_id_child"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_child_right_id_child", "child", ["right_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_child_left_id_scenario", "scenario", ["left_id"], ["id"]
        )

    with op.batch_alter_table("scenario_asset", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_asset_right_id_asset"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_asset_left_id_scenario"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_asset_left_id_scenario", "scenario", ["left_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scenario_asset_right_id_asset", "asset", ["right_id"], ["id"]
        )

    with op.batch_alter_table("scenario", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_owner_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_owner_id_account", "account", ["owner_id"], ["id"]
        )

    with op.batch_alter_table("risk", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_risk_owner_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_risk_owner_id_account", "account", ["owner_id"], ["id"]
        )

    with op.batch_alter_table("liability", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_liability_owner_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_liability_owner_id_account", "account", ["owner_id"], ["id"]
        )

    with op.batch_alter_table("income", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_income_owner_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_income_owner_id_account", "account", ["owner_id"], ["id"]
        )

    with op.batch_alter_table("house", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_house_owner_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_house_owner_id_account", "account", ["owner_id"], ["id"]
        )

    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_expense_owner_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_expense_owner_id_account", "account", ["owner_id"], ["id"]
        )

    with op.batch_alter_table("child", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_child_parent_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_child_parent_id_account", "account", ["parent_id"], ["id"]
        )

    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_asset_owner_id_account"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_asset_owner_id_account", "account", ["owner_id"], ["id"]
        )

    # ### end Alembic commands ###
