"""revised left, right id of association tables to its entities

Revision ID: c7376fb6bff6
Revises: b94ab48ea8cc
Create Date: 2025-03-28 09:26:52.114447

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7376fb6bff6"
down_revision = "b94ab48ea8cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario_asset", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("scenario_id", sa.String(length=13), nullable=False)
        )
        batch_op.add_column(sa.Column("asset_id", sa.String(length=13), nullable=False))
        batch_op.drop_constraint(
            "fk_scenario_asset_left_id_scenario", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_scenario_asset_right_id_asset", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_asset_asset_id_asset"),
            "asset",
            ["asset_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_asset_scenario_id_scenario"),
            "scenario",
            ["scenario_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("right_id")
        batch_op.drop_column("left_id")

    with op.batch_alter_table("scenario_child", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("scenario_id", sa.String(length=13), nullable=False)
        )
        batch_op.add_column(sa.Column("child_id", sa.String(length=13), nullable=False))
        batch_op.drop_constraint(
            "fk_scenario_child_left_id_scenario", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_scenario_child_right_id_child", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_child_scenario_id_scenario"),
            "scenario",
            ["scenario_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_child_child_id_child"),
            "child",
            ["child_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("right_id")
        batch_op.drop_column("left_id")

    with op.batch_alter_table("scenario_expense", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("expense_id", sa.String(length=13), nullable=False)
        )
        batch_op.drop_constraint(
            "fk_scenario_expense_right_id_expense", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_expense_expense_id_expense"),
            "expense",
            ["expense_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("right_id")

    with op.batch_alter_table("scenario_house", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("scenario_id", sa.String(length=13), nullable=False)
        )
        batch_op.add_column(sa.Column("house_id", sa.String(length=13), nullable=False))
        batch_op.drop_constraint("fk_scenario_house_right_id_house", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_scenario_house_left_id_scenario", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_house_scenario_id_scenario"),
            "scenario",
            ["scenario_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_house_house_id_house"),
            "house",
            ["house_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("right_id")
        batch_op.drop_column("left_id")

    with op.batch_alter_table("scenario_income", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("scenario_id", sa.String(length=13), nullable=False)
        )
        batch_op.add_column(
            sa.Column("income_id", sa.String(length=13), nullable=False)
        )
        batch_op.drop_constraint(
            "fk_scenario_income_right_id_income", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_scenario_income_left_id_scenario", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_income_income_id_income"),
            "income",
            ["income_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_income_scenario_id_scenario"),
            "scenario",
            ["scenario_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("right_id")
        batch_op.drop_column("left_id")

    with op.batch_alter_table("scenario_liability", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("scenario_id", sa.String(length=13), nullable=False)
        )
        batch_op.add_column(
            sa.Column("liability_id", sa.String(length=13), nullable=False)
        )
        batch_op.drop_constraint(
            "fk_scenario_liability_right_id_liability", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_scenario_liability_left_id_scenario", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_liability_scenario_id_scenario"),
            "scenario",
            ["scenario_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_liability_liability_id_liability"),
            "liability",
            ["liability_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("right_id")
        batch_op.drop_column("left_id")

    with op.batch_alter_table("scenario_risk", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("scenario_id", sa.String(length=13), nullable=False)
        )
        batch_op.add_column(sa.Column("risk_id", sa.String(length=13), nullable=False))
        batch_op.drop_constraint("fk_scenario_risk_right_id_risk", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_scenario_risk_left_id_scenario", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_risk_scenario_id_scenario"),
            "scenario",
            ["scenario_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenario_risk_risk_id_risk"),
            "risk",
            ["risk_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("right_id")
        batch_op.drop_column("left_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario_risk", schema=None) as batch_op:
        batch_op.add_column(sa.Column("left_id", sa.VARCHAR(length=13), nullable=False))
        batch_op.add_column(
            sa.Column("right_id", sa.VARCHAR(length=13), nullable=False)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_risk_risk_id_risk"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_risk_scenario_id_scenario"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_risk_left_id_scenario",
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_scenario_risk_right_id_risk",
            "risk",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("risk_id")
        batch_op.drop_column("scenario_id")

    with op.batch_alter_table("scenario_liability", schema=None) as batch_op:
        batch_op.add_column(sa.Column("left_id", sa.VARCHAR(length=13), nullable=False))
        batch_op.add_column(
            sa.Column("right_id", sa.VARCHAR(length=13), nullable=False)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_liability_liability_id_liability"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_liability_scenario_id_scenario"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_liability_left_id_scenario",
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_scenario_liability_right_id_liability",
            "liability",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("liability_id")
        batch_op.drop_column("scenario_id")

    with op.batch_alter_table("scenario_income", schema=None) as batch_op:
        batch_op.add_column(sa.Column("left_id", sa.VARCHAR(length=13), nullable=False))
        batch_op.add_column(
            sa.Column("right_id", sa.VARCHAR(length=13), nullable=False)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_income_scenario_id_scenario"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_income_income_id_income"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_income_left_id_scenario",
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_scenario_income_right_id_income",
            "income",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("income_id")
        batch_op.drop_column("scenario_id")

    with op.batch_alter_table("scenario_house", schema=None) as batch_op:
        batch_op.add_column(sa.Column("left_id", sa.VARCHAR(length=13), nullable=False))
        batch_op.add_column(
            sa.Column("right_id", sa.VARCHAR(length=13), nullable=False)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_house_house_id_house"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_house_scenario_id_scenario"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_house_left_id_scenario",
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_scenario_house_right_id_house",
            "house",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("house_id")
        batch_op.drop_column("scenario_id")

    with op.batch_alter_table("scenario_expense", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("right_id", sa.VARCHAR(length=13), nullable=False)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_expense_expense_id_expense"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_expense_right_id_expense",
            "expense",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("expense_id")

    with op.batch_alter_table("scenario_child", schema=None) as batch_op:
        batch_op.add_column(sa.Column("left_id", sa.VARCHAR(length=13), nullable=False))
        batch_op.add_column(
            sa.Column("right_id", sa.VARCHAR(length=13), nullable=False)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_child_child_id_child"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_child_scenario_id_scenario"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_child_right_id_child",
            "child",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_scenario_child_left_id_scenario",
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("child_id")
        batch_op.drop_column("scenario_id")

    with op.batch_alter_table("scenario_asset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("left_id", sa.VARCHAR(length=13), nullable=False))
        batch_op.add_column(
            sa.Column("right_id", sa.VARCHAR(length=13), nullable=False)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_asset_scenario_id_scenario"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_scenario_asset_asset_id_asset"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_scenario_asset_right_id_asset",
            "asset",
            ["right_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_scenario_asset_left_id_scenario",
            "scenario",
            ["left_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("asset_id")
        batch_op.drop_column("scenario_id")

    # ### end Alembic commands ###
