"""Chore: Add BaseYearlyGrowthRateOptionalMixin

Revision ID: edb02e791617
Revises: 016c57464b76
Create Date: 2025-03-16 22:19:04.405618

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "edb02e791617"
down_revision = "016c57464b76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario_expense", schema=None) as batch_op:
        batch_op.alter_column(
            "max_yearly_growth_rate",
            existing_type=sa.DECIMAL(precision=5, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "min_yearly_growth_rate",
            existing_type=sa.DECIMAL(precision=5, scale=2),
            nullable=True,
        )

    with op.batch_alter_table("scenario_income", schema=None) as batch_op:
        batch_op.alter_column(
            "max_yearly_growth_rate",
            existing_type=sa.DECIMAL(precision=5, scale=2),
            nullable=True,
        )
        batch_op.alter_column(
            "min_yearly_growth_rate",
            existing_type=sa.DECIMAL(precision=5, scale=2),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario_income", schema=None) as batch_op:
        batch_op.alter_column(
            "min_yearly_growth_rate",
            existing_type=sa.DECIMAL(precision=5, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "max_yearly_growth_rate",
            existing_type=sa.DECIMAL(precision=5, scale=2),
            nullable=False,
        )

    with op.batch_alter_table("scenario_expense", schema=None) as batch_op:
        batch_op.alter_column(
            "min_yearly_growth_rate",
            existing_type=sa.DECIMAL(precision=5, scale=2),
            nullable=False,
        )
        batch_op.alter_column(
            "max_yearly_growth_rate",
            existing_type=sa.DECIMAL(precision=5, scale=2),
            nullable=False,
        )

    # ### end Alembic commands ###
